### ISSUE TITLE
rlang not loaded by default for %||% (op-null-default) function

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.utils#11]
Newest version of `path_dropbox_2dii()` requires ``rlang::`%||%`()``, but `rlang` is not loaded by default.

```r
library('r2dii')
path_dropbox_2dii()
# Error in custom %||% default : could not find function "%||%" 

library('r2dii')
library('rlang')
path_dropbox_2dii()
# /Users/cjyetman/Dropbox (2° Investing)
```

**Comment by maurolepore** [comment]
Thanks for noticing that. I can't figure out what's wrong. It's puzzling because:

* I do see rlang listed in DESCRIPTION under Imports and then `%||% is imported in R/imports.R with `#' @importFrom rlang %||%`.
* R CMD check passes cleanly locally, on Docker, and on Travis.
* I can't reproduce:

``` r
library('r2dii')
#> Loading required package: r2dii.dataraw
#> Loading required package: r2dii.utils
packageVersion("r2dii.utils")
#> [1] '0.0.0.9001'
path_dropbox_2dii()
#> C:/Users/Mauro/Dropbox (2° Investing)
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Just to make sure we are talking about the same version, I incremented the dev version number to 9001. 

If the problem persists I could hack it by defininig `%||%` in R/utils.R.

**Comment by cjyetman** [comment]
I'll look into it when I get a chance (not gonna be today).

**Comment by cjyetman** [comment]
problem disappeared for me
