### ISSUE TITLE
USER.NAME vs. USER.NAME()

### ISSUE THREAD

**Issue by andybue** [2DegreesInvesting/r2dii.utils#5]
**Problem Statement**

USER.NAME is an object that represents the name of the User as a string

The r2dii package provides a function that is name USER.NAME() to identify the name of the User.

In order to implement the new function in the current code, without changing the name of the variable USER.NAME troughout the code I would have to write:

USER.NAME <- USER.NAME() 

R does not allow me to do so. 

**Possible Solution**

Rename the new function according to the new naming standard to:

user_name()

**Comment by maurolepore** [comment]
Thanks @andybue, 

Functions in r2dii (e.g. `USER.NAME()`) are not built to make it easy to work with Reference. Quite the opposite, they are designed to facilitate moving away from Reference. 

Maybe we need to discuss with @Clare2D if your effort is better put into Reference or elsewhere?

---

BTW, I moved this issue to r2dii.utils because here is where `USER.NAME()` lives. I explain the more general issue at #6. I close this issue now but feel free to continue the discussion here if it's specifically relevant to `USER.NAME()`.
